{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spreedly",
    "module": "sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.spreedly",
          "module": "paymentsheet",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.spreedly",
          "module": "hostedfields",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "result",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "network",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.1.aar",
          "url": "sdk-0.0.1.aar",
          "size": 128848,
          "sha512": "a261dc900e3c3ea72177e32f57f30a4be380ac38e12eac82423823a1658e6d6a72145d999ce9cba1f7a5ac656a0aad964fba84fcb15fb6a8c9b005c6e791b874",
          "sha256": "8c5137f6d70db783121d417fb0a991130d39597994a553ea1c7a934d9179d70b",
          "sha1": "27b3d557a1fd2bd00f58d37ddf320c8cee2dec0e",
          "md5": "c209044e6d4fb82f9ff4352bc206259f"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-core",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "ui",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "validation",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "com.spreedly",
          "module": "paymentsheet",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.spreedly",
          "module": "hostedfields",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "result",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "Spreedly-Example.core",
          "module": "network",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.1.aar",
          "url": "sdk-0.0.1.aar",
          "size": 128848,
          "sha512": "a261dc900e3c3ea72177e32f57f30a4be380ac38e12eac82423823a1658e6d6a72145d999ce9cba1f7a5ac656a0aad964fba84fcb15fb6a8c9b005c6e791b874",
          "sha256": "8c5137f6d70db783121d417fb0a991130d39597994a553ea1c7a934d9179d70b",
          "sha1": "27b3d557a1fd2bd00f58d37ddf320c8cee2dec0e",
          "md5": "c209044e6d4fb82f9ff4352bc206259f"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.0.1-sources.jar",
          "url": "sdk-0.0.1-sources.jar",
          "size": 14417,
          "sha512": "8253a010d3c8a0d5de0a12831356627af66d697e1cf563f8bc633af01fac9d1f2c20fbd57b98570505210491ac0ddc29b709145bc501ca5f9bf595558ec03722",
          "sha256": "cc4af551a40f4a0a8f761419e96bf8f4e2663d0ec76735c2e1ed9c758a3da28d",
          "sha1": "3d43b96cc7ca41936dfd0f5ee7e0a3cbe5ae6991",
          "md5": "743fc675956176d4cdaf9af034dd8a05"
        }
      ]
    }
  ]
}
